[DEFAULT]
upstream-branch = master
upstream-tag = v%(version)s
ignore-branch = True
debian-branch = debian
debian-tag = debian/v%(version)s
pristine-tar = False
export-dir = debian/build-area/

[dch]
dch-opt = --upstream
# ^^^ Don't append "ubuntu1" to the version.
commit-msg = debian: v%(version)s
