name: Packages (Debian)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Binary package
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: cd debian && sudo make deps
      - name: Build binary package
        run: cd debian && make bin/test
      - name: Upload binary package
        uses: actions/upload-artifact@v2
        with:
          name: build-area
          path: debian/build-area/
